#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<math.h>

int sort(long long A[], int n)
{
    int i, j, k, sp, ac;
    long long Temp;

    for (i=n-1; i>0; i--)
    {
        sp=1;
        for (j =0; j <i; j++)
            if (A[j] > A[j+1])
            {
                Temp = A[j];
                A[j] = A[j+1];
                A[j+1] = Temp;
                sp=0;
            }
        if (sp==1)
            break;
    }
}
///1 3 3 4 4 9 12 12 16
///
/*

16
4 8 10 14 8 16 20 28 10 20 25 35 14 28 35 49

4 9 6 6
1 2 3 4
3 3 5 6 9 15 18 15 18 30 3 3 5 6 9 15 18 15 18 30 1 9 9 25 36
4 6 8 12 6 9 12 18 8 12 16 24 12 18 24 36
16 24 48 24 36 72 48 72 144 1 4 6 12 4 6 12
4 8 12 12 8 16 24 24 12 24 36 36 12 24 36 36
1 2 5 6 7 2 4 10 12 14 5 10 25 30 35 6 12 30 36 42 7 14 35 42 49

4 9 6 6
1 2 3 4
3 3 5 6 9 15 18 15 18 30 3 3 5 6 9 15 18 15 18 30 1 9 9 25 36
4 6 8 12 6 9 12 18 8 12 16 24 12 18 24 36
16 24 48 24 36 72 48 72 144 1 4 6 12 4 6 12    ///1 4 6 12 產生可除但不是除數產生的元素
4 8 12 12 8 16 24 24 12 24 36 36 12 24 36 36
1 2 5 6 7 2 4 10 12 14 5 10 25 30 35 6 12 30 36 42 7 14 35 42 49

*/
static char buf[550] = {};
/// I still can't quiet understand why it uses static

int main()
{
    while(fgets(buf, sizeof(buf), stdin) != NULL)
        /// only read one line
        /// sizeof() returns array(or any data type you throw in)size instead of string length
        /// strlen() returns sting length (including '\0\)
        /// stdin = standard input, in this case it's the terminal
        /// when EOF or error occurs, fgets() returns NULL pointer.
    {
        int i = 0, j, k, size = 0,  as, bs;
        //fgets(buf, sizeof(buf), stdin);
        long long data[40] = {}, comp[40] = {}, ans[20] = {}, base[20], max, min;
        printf("\ninput (using fgets) = %s", buf);
        char *test = strtok(buf, " ");

        printf("\nusing strtok to seperate string\n");
        while (test != NULL)
        {
            printf("%s\n", test);
            data[size] = atoll (test);
            test = strtok(NULL, " ");
            size++;
        }
        //scanf("%d", &size);

        /*for(i = 0; i<size; i++)
        {
            scanf("%d", &data[i]);
        }*/
        printf("size = %d\n\n", size);


        sort(data, size);

        printf("sorted data[] below\n\n");
        for(i = 0; i<size; i++)
        {
            printf("%lli ", data[i]);
        }

        as = sqrt(size) - 1;

        max = sqrt(data[size-1]);
        min = sqrt(data[0]);

        printf("\nstart: %lli, end: %lli\n\n", min, max);

        j=0;
        //printf("\n\n\ni don't know what i'm doing down there\n\n\n\n");

        if(as == 0)
        {
            ans[0] = min;
        }
        if(as == 1)
        {
            ans[0] = min;
            ans[1] = max;
        }
        if(as == 2)
        {
            ans[0] = min;
            ans[1] = data[1]/min;
            ans[2] = max;
        }
        if(as == 3)
        {
            ans[0] = min;
            ans[1] = data[1]/min;
            ans[2] = data[size-2]/max;
            ans[3] = max;
        }
        if(as == 4 )
        {
            ans[0] = min;
            ans[1] = data[1]/min;
            ans[3] = data[size-2]/max;
            ans[4] = max;
            if(data[3] == data[4]){
                printf("\ncase 1 %lli/%lli\n",data[3], ans[0]);
                ans[2] = data[3]/ans[0];
            }
            if(data[size-4] == data[size-5]){
                printf("\ncase 2 %lli/%lli\n",data[size-4], ans[4]);
                ans[2] = data[size-4]/ans[4];
            }
            if(data[3] != data[4] && data[size-4] != data[size-5]){
                printf("\ncase 3 %lli/%d\lli",data[4], ans[0]);
                ans[2] = data[4]/ ans[0];
            }
        }
        printf("\nans[] = ");
        for(i = 0; i<=as; i++){
            printf("%d " ,ans[i]);
        }

        j = 0;
        printf("\nas(elements number -1) = %d\n",as);

        for(i = 0; i<=as; i++)
        {
            for(k = 0; k <=as; k++)
            {
                comp[j] = ans[i]*ans[k];
                j++;
            }
        }

        sort(comp, size);
        printf("\n\nthis is compare seq(generated by found elements)\n\n");

        for(i = 0; i<size; i++)
        {
            printf("%lli ", comp[i]);
        }

        for(i = 0; i < size; i++)
        {
            if(data[i] != comp[i])
            {
                printf("\nhelllllllll no\n");
                break;
            }
            if(i == size -1)
            {
                printf("\nyes\n");
                for(j = 0; j<=as; j++)
                {
                    printf("%d ", ans[j]);
                }
            }
        }
    }
    return 0;
}
